url: "https://lichess.org"

engine:
  dir: "/engines"
  name: "princhess"
  protocol: "uci"
  ponder: false
  polyglot:
    enabled: true
    max_depth: 4
    min_weight: 0
    selection: "uniform_random"
    book:
      standard:
        - /books/gm2001.bin
        - /books/human.bin
  uci_options:
    Threads: 2
    Hash: 1024
    SyzygyPath: /syzygy

challenge:
  concurrency: 1
  sort_by: "first"
  accept_bot: true
  variants:
    - standard
    - fromPosition

  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  modes:
    - casual
    - rated

